seed: 0
model:
    arch: senas
data:
    dataset: monusac
    train_split: train_aug
    split: val
    img_rows: 'same'
    img_cols: 'same'
searching:
    init_channels: 32
    depth: 5
    epoch: 200
    batch_size: 9
    report_freq: 10
    n_workers: 2
    alpha_begin: 10
    max_patience: 10
    gpu: True
    multi_gpus: False
    sharing_normal: False
    double_down_channel: False
    deep_supervision: False
    meta_node_num: 2
    grad_clip: 5
    train_portion: 0.5
    model_optimizer:
        name: 'sgd'
        lr: 0.025
        weight_decay: 3.0e-4
        momentum: 0.9
    arch_optimizer:
        name: 'adam'
        lr: 1.0e-4
        weight_decay: 1.0e-3
        betas: !!python/tuple [ 0.5, 0.999 ]
    loss:
        name: 'dice_ce'
        size_average: False
    resume:
training:
    geno_type: senas
    init_channels: 32
    depth: 5
    epoch: 1800
    batch_size: 12
    report_freq: 10
    n_workers: 2
    multi_gpus: False
    double_down_channel: False
    deep_supervision: False
    grad_clip: 5
    max_patience: 400
    model_optimizer:
        name: 'sgd'
        lr: 6.0e-3
        weight_decay: 5.0e-4
        momentum: 0.9
    loss:
        name: 'dice_ce'
    backbone:
    lr_schedule:
        name: 'cos'
        T_max: 100
    resume:
